#!/bin/sh -eu


PROJECT_URL=https://github.com/Simspace/simspace-provisioning/tarball/main


main ()
{
    check_preconditions
    if ! is_nix_installed
    then install_nix
    fi
    proceed_with_nix "$@"
}

check_preconditions()
{
# TODO: check GitHub access before running.
# TODO: check that user is on the VPN
# TODO: check that Homebrew is installed
}

is_nix_installed()
{
    nix_exe >/dev/null
}

install_nix()
{
    curl -L https://nixos.org/nix/install | sh
}

# TODO: change branch name from "main" to "dev"
proceed_with_nix()
{
    "$(nix_exe)" run \
        --ignore-environment \
        --keep DBUS_SESSION_BUS_ADDRESS \
        --keep HOME \
        --keep TERM \
        --keep TERMINFO \
        --keep USER \
        --file "$PROJECT_URL" \
        infra.np.nixpkgs-stable.simspace-upgrade \
        --command \
        simspace-upgrade \
        --nix "$(nix_exe)" \
        --system \
        --user \
        "$@"
}

nix_exe()
{
    command -v nix \
    || command -v /nix/var/nix/profiles/default/bin/nix
}


main "$@"
