#!/bin/sh -eu


main ()
{
    if ! is_nix_installed
    then install_nix
    fi
    proceed_with_nix "$@"
}

is_nix_installed()
{
    nix_exe >/dev/null
}

install_nix()
{
    curl -L https://nixos.org/nix/install | sh
}

proceed_with_nix()
{
    "$(nix_exe)" run \
        --ignore-environment \
        --keep DBUS_SESSION_BUS_ADDRESS \
        --keep HOME \
        --keep TERM \
        --keep TERMINFO \
        --keep USER \
        --file https:: \
        infra.np.nixpkgs-stable.simspace-upgrade \
        --command \
        simspace-home-manager \
        --nix "$(command -v nix-build)" \
        "$@"
}

nix_exe()
{
    command -v nix \
    || command -v /nix/var/nix/profiles/default/bin/nix
}

move_to_other_script()
{
    curl -L https://github.com/Simspace/simspace-provisioning/archive/refs/heads/main.zip --output simspace-provisioning.zip
    unzip simspace-provisioning.zip
    mv simspace-provisioning-main simspace-provisioning
    rm -rf simspace-provisioning.zip
}

main "$@"
