#!/bin/sh -eu


PROJECT_URL=https://github.com/Simspace/simspace-provisioning/tarball/main


main ()
{
    echo "Checking for required backing services..."
    check_preconditions
    echo "All required services found"
    if ! is_nix_installed
    then install_nix
    fi
    if is_mac && !is_nix_darwin_installed
    then install_nix_darwin
    fi
    provision "$@"
}

check_preconditions()
{
    HAS_PROBLEM=false
    for cmd in \
        curl \
        grep \
        uname
    do
        if ! command -v "$cmd" >/dev/null 2>&1
        then
            HAS_PROBLEM=true
            echo "ERROR: required command not found: $cmd"
        fi
    done
    if is_mac && ! command -v brew >/dev/null 2>&1
    then
        HAS_PROBLEM=true
        echo "ERROR: required command not found: brew"
    fi
    # TODO added a check on HAS_PROBLEM to not run this if curl isn't found
    if ! $HAS_PROBLEM && ! curl --insecure --silent https://eng.simspace.lan >/dev/null
    then
        HAS_PROBLEM=true
        echo "ERROR: do not appear connected to SimSpace VPN"
    fi
    if $HAS_PROBLEM
    then
        echo
        echo "All required services must be set up before provisioning." >&2
        echo "See errors reported above." >&2
        exit 1
    fi
}

is_nix_installed()
{
    echo "Checking for nix installation..."
    nix_exe >/dev/null
}

is_mac()
{
    echo "Checking system type..."
    test "$(uname)" = Darwin
}

install_nix()
{
    echo "No nix instillation found"
    if is_mac
    then install_nix_for_darwin
    else install_nix_for_linux
    fi
    echo "Nix installation finished"
}

install_nix_for_darwin()
{
    echo "Mac system detected installing nix for darwin..."
    curl -L https://nixos.org/nix/install \
    | sh -s -- --daemon --darwin-use-unencrypted-nix-store-volume
}

install_nix_for_linux()
{
    echo "Linux system detected installing nix for linux..."
    curl -L https://nixos.org/nix/install \
    | sh -s -- --daemon
}

is_nix_darwin_installed()
{
    echo "Checking for nix-darwin installation"
    command -v darwin-rebuild >/dev/null 2>&1
}

install_nix_darwin()
{
   echo "Installing nix-darwin..."
   # "$(nix_exe)" run \
   #     --ignore-environment \
   #     --keep HOME \
   #     --keep TERM \
   #     --keep TERMINFO \
   #     --keep USER \
   #     --file "https://github.com/LnL7/nix-darwin/archive/master.tar.gz" \
   #     installer \
   #     --command darwin-installer
}

provision()
{
    echo "Beginning system provisioning..."
    if is_mac
    then provision_darwin
    else provision_linux
    fi
}

provision_darwin()
{
    echo "Provisioning Mac..."
    "$(nix_exe)" run \
        --ignore-environment \
        --keep HOME \
        --keep TERM \
        --keep TERMINFO \
        --keep USER \
        --file "$PROJECT_URL" \
        infra.np.nixpkgs-stable.simspace-update \
        --command \
        simspace-update \
        --nix "$(nix_exe)" \
        switch
}

provision_linux()
{
    echo "Provisioning Linux..."
    "$(nix_exe)" run \
        --ignore-environment \
        --keep DBUS_SESSION_BUS_ADDRESS \
        --keep HOME \
        --keep TERM \
        --keep TERMINFO \
        --keep USER \
        --file "$PROJECT_URL" \
        infra.np.nixpkgs-stable.simspace-update \
        --command \
        simspace-update \
        --nix "$(nix_exe)" \
        --nixos-rebuild "$(nixos_exe)" \
        switch
}

nix_exe()
{
    command -v nix \
    || command -v /run/current-system/sw/bin/nix \
    || command -v /nix/var/nix/profiles/default/bin/nix
}

nixos_exe()
{
    command -v nixos-rebuild \
    || command -v /run/current-system/sw/bin/nixos-rebuild
}


main "$@"
