#!/bin/sh -eu


PROJECT_URL=https://github.com/Simspace/simspace-provisioning/tarball/main


main ()
{
    check_preconditions
    if ! is_nix_installed
    then install_nix
    fi
    proceed_with_nix "$@"
}

check_preconditions()
{
    # TODO: check GitHub access before running.
    HAS_VPN=false
    HAS_BREW=false

    # check that user is on the VPN
    if curl -sI https://eng.simspace.lan | grep "HTTP/2 200" > /dev/null ; then
        HAS_VPN=true
    else
        echo "Failure: Are you currently connected to the VPN?"
    fi

    # check that Homebrew is installed
    if brew --version | grep "command not found" > /dev/null ; then
        echo "Failure: Do you currently have Homebrew installed?"
    else
        HAS_BREW=true
    fi

    # fail if any backing service is missing
    if ! ( $HAS_VPN && $HAS_BREW ) ; then
        echo "All required services must be installed and set up before provisioning can begin."
        exit 1
    fi
}

is_nix_installed()
{
    nix_exe >/dev/null
}

install_nix()
{
    curl -L https://nixos.org/nix/install | sh
}

# TODO: change branch name from "main" to "dev"
proceed_with_nix()
{
    "$(nix_exe)" run \
        --ignore-environment \
        --keep DBUS_SESSION_BUS_ADDRESS \
        --keep HOME \
        --keep TERM \
        --keep TERMINFO \
        --keep USER \
        --file "$PROJECT_URL" \
        infra.np.nixpkgs-stable.simspace-upgrade \
        --command \
        simspace-upgrade \
        --nix "$(nix_exe)" \
        --system \
        --user \
        "$@"
}

nix_exe()
{
    command -v nix \
    || command -v /nix/var/nix/profiles/default/bin/nix
}


main "$@"
