#!/bin/sh -eu

cd "$(dirname "$0")"

nix run \
    --ignore-environment \
    --file . \
    infra.np.nixpkgs-stable.simspace-nixos-rebuild \
    --command \
    simspace-nixos-rebuild \
    --nixos-exe "$(command -v nixos-rebuild)" \
    "$@"
